<script setup lang="ts">
import { onMounted, ref } from "vue";

import type { AdminApi, ModelProfile, PromptVersion, ExecutionPolicy } from "./api";
const props = defineProps<{ api: AdminApi }>();
const profiles = ref<ModelProfile[]>([]); const prompts = ref<PromptVersion[]>([]); const policies = ref<ExecutionPolicy[]>([]); const loading = ref(false); const error = ref("");
async function load() { loading.value=true; error.value=""; try { const [modelProfiles, promptVersions, executionPolicies] = await Promise.all([props.api.modelProfiles(),props.api.prompts(),props.api.policies()]); profiles.value=modelProfiles; prompts.value=promptVersions; policies.value=executionPolicies; } catch(cause) { error.value=cause instanceof Error ? cause.message : "无法加载模型与策略"; } finally { loading.value=false; } }
onMounted(load);
</script>
<template>
  <section class="admin-card" aria-labelledby="policy-heading"><header><div><h2 id="policy-heading">模型与策略</h2><p>模型密钥只显示凭证引用，配置以服务端已发布版本为准。</p></div><button type="button" :disabled="loading" @click="load">刷新</button></header><p v-if="loading" class="state">正在加载模型与策略…</p><p v-else-if="error" class="error" role="alert">{{ error }} <button type="button" @click="load">重试</button></p><template v-if="!loading && !error"><section><h3>模型档案</h3><p v-if="!profiles.length" class="state">尚未配置模型档案。</p><div v-else class="cards"><article v-for="profile in profiles" :key="profile.id"><strong>{{ profile.name }}</strong><span>{{ profile.provider }} · {{ profile.model }}</span><small>{{ profile.region ?? "默认地域" }} · {{ profile.enabled ? "已启用" : "已停用" }}</small><small>凭证：{{ profile.credentialRef ?? "未配置" }}</small></article></div></section><section><h3>提示词版本</h3><p v-if="!prompts.length" class="state">尚未发布提示词版本。</p><ul v-else class="plain-list"><li v-for="prompt in prompts" :key="prompt.id"><strong>{{ prompt.name }}</strong><span>v{{ prompt.version }}</span><span>{{ prompt.active ? "已启用" : "未启用" }}</span><small>{{ prompt.createdAt ?? "—" }}</small></li></ul></section><section><h3>执行预算与检索参数</h3><p v-if="!policies.length" class="state">尚未配置执行策略。</p><div v-for="policy in policies" v-else :key="policy.id" class="policy"><strong>{{ policy.type }} · v{{ policy.version }}</strong><span>{{ policy.active ? "已启用" : "未启用" }}</span><code>{{ policy.configuration }}</code><small>{{ policy.createdAt ?? "—" }}</small></div></section></template></section>
</template>
<style scoped>
.admin-card { display:grid; gap:1.1rem; }.admin-card header { display:flex; justify-content:space-between; gap:1rem; }.admin-card h2,.admin-card h3,.admin-card p { margin:0; }.admin-card h3 { margin-bottom:.5rem; font-size:.95rem; }.admin-card header p,.state,small { color:#55706f; font-size:.85rem; }.cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(12rem,1fr)); gap:.65rem; }.cards article { display:grid; gap:.25rem; padding:.75rem; border:1px solid #d9e9e5; border-radius:.55rem; }.cards span { font-size:.86rem; }.plain-list { display:grid; gap:.4rem; margin:0; padding:0; list-style:none; }.plain-list li { display:flex; flex-wrap:wrap; gap:.6rem; padding:.55rem; border-bottom:1px solid #e5efed; font-size:.84rem; }.policy { display:grid; grid-template-columns:repeat(auto-fit,minmax(8rem,1fr)); gap:.6rem; align-items:end; padding:.75rem; border:1px solid #d9e9e5; border-radius:.55rem; }.policy strong { grid-column:1/-1; }.policy label { display:grid; gap:.25rem; color:#55706f; font-size:.78rem; }.policy input[type="number"] { min-height:2.1rem; padding:0 .45rem; border:1px solid #cfe2de; border-radius:.4rem; }.policy .enabled { display:flex; gap:.4rem; align-items:center; min-height:2.1rem; }.error { color:#b42318; }.notice { color:#17675f; } button { padding:.42rem .7rem; border:1px solid #20756d; border-radius:.4rem; color:#17675f; background:white; cursor:pointer; }
</style>
