<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";

import type { AdminApi, UsageFilters, UsageReport } from "./api";
const props = defineProps<{ api: AdminApi }>();
const filters = reactive<UsageFilters>({}); const report = ref<UsageReport | null>(null); const loading = ref(false); const error = ref("");
const totals = computed(() => (report.value?.items ?? []).reduce((total, item) => ({ requests: total.requests + item.requestCount, success: total.success + item.successCount, input: total.input + (item.inputTokens ?? 0), output: total.output + (item.outputTokens ?? 0), unknown: total.unknown + item.unknownUsageCount, cost: total.cost + (item.estimatedCost ?? 0) }), { requests:0, success:0, input:0, output:0, unknown:0, cost:0 }));
async function load() { loading.value=true; error.value=""; try { report.value=await props.api.usage(filters); } catch (cause) { error.value=cause instanceof Error ? cause.message : "无法加载用量统计"; } finally { loading.value=false; } }
onMounted(load);
</script>
<template>
  <section class="admin-card" aria-labelledby="usage-heading"><header><div><h2 id="usage-heading">用量统计</h2><p>按用户、模型、方式和用途聚合；未知用量不会当作零。</p></div><button type="button" :disabled="loading" @click="load">刷新</button></header><form class="filters" @submit.prevent="load"><input v-model="filters.userId" placeholder="用户 ID" aria-label="用户 ID"/><input v-model="filters.model" placeholder="模型" aria-label="模型"/><select v-model="filters.mode" aria-label="执行方式"><option value="">全部方式</option><option>AUTO_KB</option><option>MANUAL_KB</option><option>AGENT</option></select><input v-model="filters.purpose" placeholder="用途" aria-label="用途"/><input v-model="filters.from" type="date" aria-label="开始日期"/><input v-model="filters.to" type="date" aria-label="结束日期"/><button type="submit" :disabled="loading">筛选</button></form><p v-if="loading" class="state">正在加载用量统计…</p><p v-else-if="error" class="error" role="alert">{{ error }} <button type="button" @click="load">重试</button></p><template v-else><div class="metrics"><div><strong>{{ totals.requests }}</strong><span>请求数</span></div><div><strong>{{ totals.requests ? Math.round(totals.success / totals.requests * 100) : 0 }}%</strong><span>成功率</span></div><div><strong>{{ totals.input + totals.output }}</strong><span>已知 Token</span></div><div><strong>{{ totals.unknown }}</strong><span>未知用量项</span></div><div><strong>{{ totals.cost.toFixed(4) }}</strong><span>估算费用</span></div></div><p v-if="report?.syncedAt" class="state">同步时间：{{ report.syncedAt }}</p><p v-if="!report?.items.length" class="state">没有符合条件的用量记录。</p><div v-else class="table-wrap"><table><thead><tr><th>日期</th><th>用户 / 模型</th><th>方式 / 用途</th><th>请求 / 成功</th><th>Token</th><th>未知</th><th>费用</th></tr></thead><tbody><tr v-for="row in report.items" :key="`${row.date}:${row.userId}:${row.model}:${row.purpose}`"><td>{{ row.date ?? "汇总" }}</td><td>{{ row.username ?? row.userId ?? "全部" }}<small>{{ row.model ?? "全部模型" }}</small></td><td>{{ row.mode ?? "全部" }}<small>{{ row.purpose ?? "全部用途" }}</small></td><td>{{ row.requestCount }} / {{ row.successCount }}</td><td>{{ row.inputTokens ?? "—" }} / {{ row.outputTokens ?? "—" }}</td><td>{{ row.unknownUsageCount }}</td><td>{{ row.estimatedCost ?? "未定价" }} {{ row.currency ?? "" }}</td></tr></tbody></table></div></template></section>
</template>
<style scoped>
.admin-card { display:grid; gap:1rem; }.admin-card header { display:flex; justify-content:space-between; gap:1rem; }.admin-card h2,.admin-card p { margin:0; }.admin-card header p,.state,small { color:#55706f; font-size:.85rem; }.filters { display:flex; flex-wrap:wrap; gap:.55rem; }.filters input,.filters select { min-height:2.25rem; padding:0 .55rem; border:1px solid #cfe2de; border-radius:.45rem; }.metrics { display:grid; grid-template-columns:repeat(auto-fit,minmax(8rem,1fr)); gap:.6rem; }.metrics div { display:grid; gap:.2rem; padding:.75rem; border-radius:.55rem; background:#eef7f5; }.metrics strong { font-size:1.25rem; }.metrics span { color:#55706f; font-size:.8rem; }.table-wrap { overflow:auto; } table { width:100%; border-collapse:collapse; font-size:.84rem; } th,td { padding:.6rem .5rem; border-bottom:1px solid #e5efed; text-align:left; } td small { display:block; margin-top:.2rem; } button { padding:.42rem .7rem; border:1px solid #20756d; border-radius:.4rem; color:#17675f; background:white; cursor:pointer; }.error { color:#b42318; }
</style>
