<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";

import type { AdminApi, AdminUser } from "./api";
const props = defineProps<{ api: AdminApi }>();
const users = ref<AdminUser[]>([]); const loading = ref(false); const error = ref(""); const notice = ref("");
const newUser = reactive({ username: "", displayName: "", password: "", role: "USER" as "USER" | "ADMIN" });
const resetUserId = ref(""); const resetPasswordValue = ref("");
async function load() { loading.value=true; error.value=""; try { users.value=await props.api.listUsers(); } catch(cause) { error.value=cause instanceof Error ? cause.message : "无法加载用户"; } finally { loading.value=false; } }
async function create() { notice.value=""; try { await props.api.createUser({ ...newUser }); newUser.username=""; newUser.displayName=""; newUser.password=""; notice.value="用户已创建。"; await load(); } catch(cause) { error.value=cause instanceof Error ? cause.message : "无法创建用户"; } }
async function toggle(user: AdminUser) { notice.value=""; try { await props.api.setUserEnabled(user.id, !user.active); notice.value=user.active ? "用户已禁用，现有登录令牌将在认证版本更新后失效。" : "用户已启用。"; await load(); } catch(cause) { error.value=cause instanceof Error ? cause.message : "无法更新用户状态"; } }
async function resetPassword() { if (!resetUserId.value || !resetPasswordValue.value) return; try { await props.api.resetPassword(resetUserId.value, resetPasswordValue.value); resetPasswordValue.value=""; notice.value="密码已重置，用户需要重新登录。"; } catch(cause) { error.value=cause instanceof Error ? cause.message : "无法重置密码"; } }
onMounted(load);
</script>
<template>
  <section class="admin-card" aria-labelledby="user-heading"><header><div><h2 id="user-heading">用户管理</h2><p>创建、禁用和重置密码均由管理员完成。</p></div><button type="button" :disabled="loading" @click="load">刷新</button></header><p v-if="error" class="error" role="alert">{{ error }} <button type="button" @click="load">重试</button></p><p v-if="notice" class="notice" role="status">{{ notice }}</p><div class="forms"><form @submit.prevent="create"><h3>创建用户</h3><input v-model="newUser.username" required maxlength="64" placeholder="用户名" aria-label="新用户名"/><input v-model="newUser.displayName" required maxlength="128" placeholder="显示名称" aria-label="显示名称"/><input v-model="newUser.password" required minlength="12" type="password" placeholder="初始密码（至少 12 位）" aria-label="初始密码"/><select v-model="newUser.role" aria-label="新用户角色"><option value="USER">普通用户</option><option value="ADMIN">管理员</option></select><button type="submit">创建</button></form><form @submit.prevent="resetPassword"><h3>重置密码</h3><select v-model="resetUserId" required aria-label="重置密码用户"><option value="" disabled>选择用户</option><option v-for="user in users" :key="user.id" :value="user.id">{{ user.username }}</option></select><input v-model="resetPasswordValue" required minlength="12" type="password" placeholder="新密码（至少 12 位）" aria-label="新密码"/><button type="submit">重置</button></form></div><p v-if="loading" class="state">正在加载用户…</p><p v-else-if="!users.length" class="state">没有可管理的用户。</p><div v-else class="table-wrap"><table><thead><tr><th>用户名</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td>{{ user.username }}<small>{{ user.displayName }} · {{ user.id }}</small></td><td>{{ user.role }}</td><td>{{ user.active ? "启用" : "禁用" }}</td><td><button type="button" @click="toggle(user)">{{ user.active ? "禁用" : "启用" }}</button></td></tr></tbody></table></div></section>
</template>
<style scoped>
.admin-card { display:grid; gap:1rem; }.admin-card header { display:flex; justify-content:space-between; gap:1rem; }.admin-card h2,.admin-card h3,.admin-card p { margin:0; }.admin-card header p,.state,small { color:#55706f; font-size:.85rem; }.forms { display:grid; grid-template-columns:repeat(auto-fit,minmax(13rem,1fr)); gap:.75rem; }.forms form { display:grid; gap:.5rem; padding:.8rem; border:1px solid #d9e9e5; border-radius:.55rem; }.forms input,.forms select { min-height:2.25rem; padding:0 .55rem; border:1px solid #cfe2de; border-radius:.45rem; }.table-wrap { overflow:auto; } table { width:100%; border-collapse:collapse; font-size:.84rem; } th,td { padding:.6rem .5rem; border-bottom:1px solid #e5efed; text-align:left; } td small { display:block; margin-top:.2rem; } button { padding:.42rem .7rem; border:1px solid #20756d; border-radius:.4rem; color:#17675f; background:white; cursor:pointer; }.error { color:#b42318; }.notice { color:#17675f; }
</style>
